In [37]:
import torch
import numpy as np

In [8]:
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())

0.4.1
None
False


### Tensor Attributes

In [33]:
dd = [[1,3,4,5],[1,5,6,7],[6,7,4,7]]
t = torch.tensor(dd)

In [36]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.int64
cpu
torch.strided


In [18]:
t

tensor([[1, 3, 4, 5],
        [1, 5, 6, 7],
        [6, 7, 4, 7]])

In [19]:
type(t)

torch.Tensor

In [20]:
type(dd)

list

In [21]:
t.shape

torch.Size([3, 4])

In [24]:
rank = len(t.shape)
print(rank)

2


In [25]:
t.reshape(1,12)

tensor([[1, 3, 4, 5, 1, 5, 6, 7, 6, 7, 4, 7]])

In [26]:
t.reshape(12,1)

tensor([[1],
        [3],
        [4],
        [5],
        [1],
        [5],
        [6],
        [7],
        [6],
        [7],
        [4],
        [7]])

In [27]:
t.reshape(3,4)

tensor([[1, 3, 4, 5],
        [1, 5, 6, 7],
        [6, 7, 4, 7]])

In [30]:
t.reshape(4,3)

tensor([[1, 3, 4],
        [5, 1, 5],
        [6, 7, 6],
        [7, 4, 7]])

In [31]:
t.reshape(2,6)

tensor([[1, 3, 4, 5, 1, 5],
        [6, 7, 6, 7, 4, 7]])

In [32]:
t.reshape(6,2)

tensor([[1, 3],
        [4, 5],
        [1, 5],
        [6, 7],
        [6, 7],
        [4, 7]])

In [38]:
data = np.array([1,3,4,5,6])

In [39]:
t1 = torch.Tensor(data)

In [40]:
t2 = torch.tensor(data)

In [41]:
t3 = torch.as_tensor(data)

In [42]:
t4 = torch.from_numpy(data)

In [48]:
t1.dtype

torch.float32

In [49]:
t2.dtype

torch.int64

In [50]:
t3.dtype

torch.int64

In [51]:
t4.dtype

torch.int64

In [54]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [58]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [59]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [60]:
torch.rand(3,4)

tensor([[0.7128, 0.8675, 0.4238, 0.1025],
        [0.8757, 0.7138, 0.5794, 0.9547],
        [0.9331, 0.8828, 0.4483, 0.1848]])

In [67]:
torch.rand(2)

tensor([0.3866, 0.0896])