In [37]:
import torch
import numpy as np

In [8]:
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())

0.4.1
None
False


### Tensor Attributes

In [33]:
dd = [[1,3,4,5],[1,5,6,7],[6,7,4,7]]
t = torch.tensor(dd)

In [36]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.int64
cpu
torch.strided


In [18]:
t

tensor([[1, 3, 4, 5],
        [1, 5, 6, 7],
        [6, 7, 4, 7]])

In [19]:
type(t)

torch.Tensor

In [20]:
type(dd)

list

In [21]:
t.shape

torch.Size([3, 4])

In [24]:
rank = len(t.shape)
print(rank)

2


In [25]:
t.reshape(1,12)

tensor([[1, 3, 4, 5, 1, 5, 6, 7, 6, 7, 4, 7]])

In [26]:
t.reshape(12,1)

tensor([[1],
        [3],
        [4],
        [5],
        [1],
        [5],
        [6],
        [7],
        [6],
        [7],
        [4],
        [7]])

In [27]:
t.reshape(3,4)

tensor([[1, 3, 4, 5],
        [1, 5, 6, 7],
        [6, 7, 4, 7]])

In [30]:
t.reshape(4,3)

tensor([[1, 3, 4],
        [5, 1, 5],
        [6, 7, 6],
        [7, 4, 7]])

In [31]:
t.reshape(2,6)

tensor([[1, 3, 4, 5, 1, 5],
        [6, 7, 6, 7, 4, 7]])

In [32]:
t.reshape(6,2)

tensor([[1, 3],
        [4, 5],
        [1, 5],
        [6, 7],
        [6, 7],
        [4, 7]])

In [38]:
data = np.array([1,3,4,5,6])

In [39]:
t1 = torch.Tensor(data)

In [40]:
t2 = torch.tensor(data)

In [41]:
t3 = torch.as_tensor(data)

In [42]:
t4 = torch.from_numpy(data)

In [48]:
t1.dtype

torch.float32

In [49]:
t2.dtype

torch.int64

In [50]:
t3.dtype

torch.int64

In [51]:
t4.dtype

torch.int64

In [54]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [69]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [59]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [60]:
torch.rand(3,4)

tensor([[0.7128, 0.8675, 0.4238, 0.1025],
        [0.8757, 0.7138, 0.5794, 0.9547],
        [0.9331, 0.8828, 0.4483, 0.1848]])

In [67]:
torch.rand(2)

tensor([0.3866, 0.0896])

In [70]:
torch.get_default_dtype()

torch.float32

In [74]:
torch.tensor(data, dtype = torch.int8)

tensor([1, 3, 4, 5, 6], dtype=torch.int8)

In [75]:
t5 = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype = torch.float32)

In [76]:
t5

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [78]:
t.size()

torch.Size([3, 4])

In [79]:
t.shape

torch.Size([3, 4])

In [80]:
t.numel()

12

In [81]:
torch.tensor(t.shape).prod()

tensor(12)

In [82]:
t

tensor([[1, 3, 4, 5],
        [1, 5, 6, 7],
        [6, 7, 4, 7]])

### Reshape, Squeeze & Flatten

In [87]:
t.reshape(1,12).squeeze().unsqueeze(dim=0)

tensor([[1, 3, 4, 5, 1, 5, 6, 7, 6, 7, 4, 7]])

In [88]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [90]:
data = np.array([[1,2,4],[1,4,5],[5,6,7],[0,9,0]])
t = torch.tensor(data)

flatten(t)

tensor([1, 2, 4, 1, 4, 5, 5, 6, 7, 0, 9, 0])

In [98]:
t.reshape(-1)

tensor([1, 2, 4, 1, 4, 5, 5, 6, 7, 0, 9, 0])

In [116]:
t.view(-1)

tensor([1, 2, 4, 1, 4, 5, 5, 6, 7, 0, 9, 0])

In [117]:
t.view(t.numel())

tensor([1, 2, 4, 1, 4, 5, 5, 6, 7, 0, 9, 0])

In [119]:
t.reshape(1,-1)[0]

tensor([1, 2, 4, 1, 4, 5, 5, 6, 7, 0, 9, 0])

In [120]:
t.flatten()

tensor([1, 2, 4, 1, 4, 5, 5, 6, 7, 0, 9, 0])

In [121]:
t2 = torch.tensor([[5,6,7]])

In [122]:
torch.cat((t,t2), dim=0)

tensor([[1, 2, 4],
        [1, 4, 5],
        [5, 6, 7],
        [0, 9, 0],
        [5, 6, 7]])

In [106]:
t3 = t2.reshape(-1)

In [108]:
t4 = t.reshape(-1)

In [115]:
torch.cat((t3,t4),dim=0)

tensor([5, 6, 7, 1, 2, 4, 1, 4, 5, 5, 6, 7, 0, 9, 0])

#### Broadcasting


In [123]:
d1 = np.array([[1,3,5],[3,6,7]])

In [126]:
t1 = torch.tensor([1,4,5])

In [127]:
np.broadcast_to(t1.numpy(), d1.shape)

array([[1, 4, 5],
       [1, 4, 5]])

#### Reduction Operations

In [133]:
t = torch.tensor([[1,1,1,1],
                 [2,2,2,2],
                 [3,3,3,3],
                 [4,4,4,4]],dtype = torch.float32)

In [134]:
t.sum()

tensor(40.)

In [135]:
t.sum(dim=0)

tensor([10., 10., 10., 10.])

In [136]:
t.sum(dim=1)

tensor([ 4.,  8., 12., 16.])

In [137]:
t.mean(dim=1)

tensor([1., 2., 3., 4.])

In [138]:
t.prod()

tensor(331776.)

In [143]:
t.mean().item()

2.5

In [144]:
type(t.mean().item())

float

In [146]:
t.sum(dim=0).tolist()

[10.0, 10.0, 10.0, 10.0]

In [147]:
t.sum(dim=0).numpy()

array([ 10.,  10.,  10.,  10.], dtype=float32)